### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [tajul-saajan/google-searcher#7]
Hello Tajul 👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

**Comment by olivierobert** [comment]
I have now completed the initial round of reviews. I have focused on the key issues to ensure we can keep the whole process within the allotted time. 

I am now looking forward to hearing from you on all open issues 🙏

**Comment by tajul-saajan** [comment]
Hi,

Thank you for reviewing my coding task and for the valuable feedback. I noticed the issues you've raised and would like to clarify the order of priority for addressing them. Should I tackle them in the order they were created, prioritize feature-related issues, or is there flexibility to address them arbitrarily? Your guidance on this would be greatly appreciated.

Again, thank you for your time and effort in reviewing my code. I am looking forward to working with you to make the necessary improvements.

**Comment by tajul-saajan** [comment]
Anyway, I have already started working on the issues. I have prioritized them according to their time duration as per my initial estimation. I hope you consider any inconvenience

**Comment by olivierobert** [comment]
At a minimum, I would like you to respond to the open issues. Since we have only 1 day left to wrap up this stage of the process, I do not expect fixes for all issues. I am interested on your approach and understanding how you think about the issues.

**Comment by olivierobert** [comment]
After reviewing the pull requests, as a general comment, you need to make sure that each pull request only contains the changes for one issue. It appears that each PR build on the previous one, hence contain unrelated changes 🙈 

I will now let you review my comments and give you some time to respond to them. Let's aim to wrap up the code review by tomorrow 🙏

**Comment by tajul-saajan** [comment]
It might revert my previous changes if I do not make PR on the previous change. And I have to make multiple PRs. Although I do not follow this approach in my day-to-day tasks, I decided to make a branch on top of the previous one due to this unique situation.
Anyway, for any specific branch, I can make PR to its base branch so that it shows only the changes I have made on that specific branch.

**Comment by olivierobert** [comment]
Thank you for your efforts in the code challenge and code review. It is now time for us to wrap up this stage of the recruitment process. Our apologies for the delays in marking this complete. Our team currently has many candidates in parallel and I had some unavailabilities. Still, I hope this process was helpful to you as you expressed. Thank you 🙏
